<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ProjectExtensions><VisualStudio><UserProperties land_3grapics_1json__JsonSchema="..\..\С#\CASurvive\surfaces.schema.json" settings_1json__JsonSchema="..\..\С#\CASurvive\surfaces.schema.json" /></VisualStudio></ProjectExtensions>

  <ItemGroup>
    <None Update="cover_templates.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
